feat: configure stitches and add commons
perfarm/frontend pull request #1
Opened 2023-05-12 11:31 UTC by deyvison-costa

stitches configuration

2023-05-12 20:38 UTC, ivanguimam requested changes

2023-05-12 20:38 UTC, ivanguimam commented on src/theme/index.ts
> +      error50: '#FFEBEE',
Esse grupo de `error` pode apagar ele não faz parte do nosso design system, temos que remover do `ui-kit` depois

2023-05-12 20:38 UTC, ivanguimam commented on src/theme/index.ts
> +      gray50: '#fafafa',
Esse grupo de `gray` pode apagar ele não faz parte do nosso design system, temos que remover do `ui-kit` depois

2023-05-12 20:38 UTC, ivanguimam commented on src/theme/index.ts
> +      primary50: '#e5f5ea',
Esse grupo de `primary` pode apagar ele não faz parte do nosso design system, temos que remover do `ui-kit` depois

2023-05-12 20:38 UTC, ivanguimam commented on src/theme/index.ts
> +      secondary50: '#fff8e0',
Esse grupo de `secondary` pode apagar ele não faz parte do nosso design system, temos que remover do `ui-kit` depois

2023-05-12 20:38 UTC, ivanguimam commented on src/theme/index.ts
> +      success50: '#E8F5E9',
Esse grupo de `success` pode apagar ele não faz parte do nosso design system, temos que remover do `ui-kit` depois

2023-05-12 20:38 UTC, ivanguimam commented on src/theme/index.ts
> +    radii: {
Nossos border radius serão `6px`, `10px`, `16px` e `24px`

Nesse link tem os tipos de border radius que vamos usar (convidei seu e-mail seedz para poder ver o arquivo): https://www.figma.com/file/uPUee2yjEsGKgD9XZHYxSe/%5BD2F%5D-Design-System?type=design&node-id=761%3A86813&t=mlQ6E3W7te6MLOYr-1

2023-05-12 21:22 UTC, deyvison-costa commented
blz vou arrumar aqui agora


On Fri, May 12, 2023 at 5:38 PM Ivan Guimarães Monte <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In src/theme/index.ts
> <https://github.com/perfarm/frontend/pull/1#discussion_r1192773070>:
>
> > +    lg: '(min-width: 1200px)',
> +    md: '(min-width: 900px)',
> +    sm: '(min-width: 600px)',
> +    xl: '(min-width: 1536px)',
> +    xs: '(min-width: 0px)',
> +  },
> +  theme: {
> +    colors: {
> +      black: '#000',
> +
> +      blackOpacity1: 'rgba(0, 0, 0, 0.1)',
> +      blackOpacity3: 'rgba(0, 0, 0, 0.3)',
> +      blackOpacity5: 'rgba(0, 0, 0, 0.5)',
> +      blackOpacity9: 'rgba(0, 0, 0, 0.9)',
> +
> +      error50: '#FFEBEE',
>
> Esse grupo de error pode apagar ele não faz parte do nosso design system,
> temos que remover do ui-kit depois
> ------------------------------
>
> In src/theme/index.ts
> <https://github.com/perfarm/frontend/pull/1#discussion_r1192773123>:
>
> > +      blackOpacity3: 'rgba(0, 0, 0, 0.3)',
> +      blackOpacity5: 'rgba(0, 0, 0, 0.5)',
> +      blackOpacity9: 'rgba(0, 0, 0, 0.9)',
> +
> +      error50: '#FFEBEE',
> +      error100: '#ffcdd2',
> +      error200: '#EF9A9A',
> +      error300: '#e57373',
> +      error400: '#EF5350',
> +      error500: '#f44236',
> +      error600: '#e53835',
> +      error700: '#d32e2f',
> +      error800: '#c62728',
> +      error900: '#b71b1c',
> +
> +      gray50: '#fafafa',
>
> Esse grupo de gray pode apagar ele não faz parte do nosso design system,
> temos que remover do ui-kit depois
> ------------------------------
>
> In src/theme/index.ts
> <https://github.com/perfarm/frontend/pull/1#discussion_r1192773197>:
>
> > +      error700: '#d32e2f',
> +      error800: '#c62728',
> +      error900: '#b71b1c',
> +
> +      gray50: '#fafafa',
> +      gray100: '#f5f5f5',
> +      gray200: '#eeeeee',
> +      gray300: '#e0e0e0',
> +      gray400: '#bdbdbd',
> +      gray500: '#9e9e9e',
> +      gray600: '#757575',
> +      gray700: '#616161',
> +      gray800: '#424242',
> +      gray900: '#212121',
> +
> +      primary50: '#e5f5ea',
>
> Esse grupo de primary pode apagar ele não faz parte do nosso design
> system, temos que remover do ui-kit depois
> ------------------------------
>
> In src/theme/index.ts
> <https://github.com/perfarm/frontend/pull/1#discussion_r1192773314>:
>
> > +      gray700: '#616161',
> +      gray800: '#424242',
> +      gray900: '#212121',
> +
> +      primary50: '#e5f5ea',
> +      primary100: '#bfe5cc',
> +      primary200: '#96d4ac',
> +      primary300: '#69c48c',
> +      primary400: '#43b874',
> +      primary500: '#04ab5c',
> +      primary600: '#009d52',
> +      primary700: '#008b46',
> +      primary800: '#00793b',
> +      primary900: '#005a27',
> +
> +      secondary50: '#fff8e0',
>
> Esse grupo de secondary pode apagar ele não faz parte do nosso design
> system, temos que remover do ui-kit depois
> ------------------------------
>
> In src/theme/index.ts
> <https://github.com/perfarm/frontend/pull/1#discussion_r1192773460>:
>
> > +      primary700: '#008b46',
> +      primary800: '#00793b',
> +      primary900: '#005a27',
> +
> +      secondary50: '#fff8e0',
> +      secondary100: '#feedb0',
> +      secondary200: '#fee17c',
> +      secondary300: '#fdd644',
> +      secondary400: '#fdcc06',
> +      secondary500: '#fdc300',
> +      secondary600: '#feb400',
> +      secondary700: '#ffa100',
> +      secondary800: '#ff8f00',
> +      secondary900: '#ff6d00',
> +
> +      success50: '#E8F5E9',
>
> Esse grupo de success pode apagar ele não faz parte do nosso design
> system, temos que remover do ui-kit depois
> ------------------------------
>
> In src/theme/index.ts
> <https://github.com/perfarm/frontend/pull/1#discussion_r1192774294>:
>
> > +      warningRedWhitened: '#FEF6F6',
> +    },
> +    fonts: {
> +      montserrat: 'Montserrat',
> +    },
> +    fontSizes: {
> +      1: '1.2rem',
> +      2: '1.4rem',
> +      3: '1.6rem',
> +      4: '2rem',
> +      5: '2.4rem',
> +      6: '2.8rem',
> +      7: '3.2rem',
> +    },
> +
> +    radii: {
>
> Nossos border radius serão 6px, 10px, 16px e 24px
>
> Nesse link tem os tipos de border radius que vamos usar (convidei seu
> e-mail seedz para poder ver o arquivo):
> https://www.figma.com/file/uPUee2yjEsGKgD9XZHYxSe/%5BD2F%5D-Design-System?type=design&node-id=761%3A86813&t=mlQ6E3W7te6MLOYr-1
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/perfarm/frontend/pull/1#pullrequestreview-1425120677>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6JZIF4TRNO5POCFFHMOOVDXF2NUTANCNFSM6AAAAAAX7MWQMQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-05-15 19:02 UTC, ivanguimam approved these changes

2023-05-15 21:05 UTC, merged