Feature/48647/add permissions logic
perfarm/frontend pull request #10
Opened 2023-07-03 16:53 UTC by deyvison-costa

# Título

### 48647 - Adicionar lógica de permissões no menu

## Motivação

Validar permissões dos clientes

## Solução proposta

Foi criada uma série de regras para assegurar que determinadas opções na Sidebar só aparecerão mediante a permissões específicas .

- Card: [48647 - Adicionar lógica de permissões no menu](https://dev.azure.com/Seedz/D2F%20-%20Perfarm/_sprints/taskboard/Projeto%20Germinacao/D2F%20-%20Perfarm/Lateral%20menu?workitem=48647)

## Checklist:

- [x] Meu código segue os padrões definidos no projeto
- [x] Realizei uma autorrevisão do meu código
- [x] Adicionei testes que provam que minha correção é eficaz ou que meu recurso funciona
- [x] Testes de unidade novos e existentes passam localmente com minhas alterações
- [ ] Meus componentes possuem storybook

2023-07-03 17:22 UTC, ivanguimam requested changes

2023-07-03 17:22 UTC, ivanguimam commented on src/hooks/usePermission.tsx
> +export const usePermission = () => {
```ts
export const usePermission = () => useContext(PermissionContext);
```

2023-07-03 17:22 UTC, ivanguimam commented on utils/BackendServer/route/GetPermissionUser/index.ts
> +    return {
Criar `factory` e utiliza-la nos testes

2023-07-03 17:22 UTC, ivanguimam commented on src/commons/api/fetchPermissions/test.ts
> +    const permissions = ['read', 'write'];
Usar a factory

2023-07-03 17:22 UTC, ivanguimam commented on src/components/Sidebar/index.tsx
> +        setItems((items) => {
```ts
const buildIndividualProduct = (link) => ({
  ...link,
  icon: Cattle as FC<Props>,
  label: link.name,
  show: () => true,
  url: `/products/${link.id}/individual_products`,
});

setItems((items) => {
  return items.map((item) => {
    if (item.title === 'DADOS INDIVIDUAIS' && item.show(permission)) {
      item.links = data?.map(buildIndividualProduct);
    }

    return item;
  });
});
```

2023-07-04 14:59 UTC, ivanguimam requested changes

2023-07-04 14:59 UTC, ivanguimam commented on src/components/Iframe/test.tsx
> +      expect(iframe).toHaveAttribute('src', 'https://google.com');
Pq você mudou a rota pra Google? O ideal é testar se ta gerando a `url` certa com o link da perfarm e o query params da navbar

2023-07-04 14:59 UTC, ivanguimam commented on src/components/Sidebar/menuItems/index.tsx
>  /* eslint-disable sort-keys */
* Remover regra
* Tipar menuItens
* Nos métodos `show`, não precisa ficar colocando `: UserPermission` depois que configurar a tipagem

src/components/Sidebar/menuItems/index.tsx
```ts
import { MenuItem } from './types';

export const menuItems: MenuItem[] = ...
```

src/components/Sidebar/menuItems/types.ts
```ts
import { FC } from "react";

import { UserPermission } from "~/commons/api/fetchPermissions/types";

export interface Link {
  show: Show;
  icon: FC;
  label: string;
  url: string;
}

export type Show = (permission: UserPermission) => boolean;

export interface MenuItem {
  links: Link[];
  show: Show;
  title: string;
}
```

2023-07-04 14:59 UTC, ivanguimam commented on src/components/Sidebar/utils/buildIndividualProduct/index.tsx
> +export const buildIndividualProduct = (link) => ({
```ts
import { Link } from 'src/components/Sidebar/menuItems/types.ts';

export const buildIndividualProduct = (link: MenuProduct): Link => ({
```

2023-07-04 14:59 UTC, ivanguimam commented on src/components/Sidebar/utils/buildIndividualProduct/index.tsx
> +  icon: Crosshair as FC<Props>,
Não precisa desse `as FC<Props>`

2023-07-04 14:59 UTC, ivanguimam commented on src/components/Sidebar/utils/truncateLabel/test.tsx
> -  it('should truncate the label and append "..." if its length exceeds the maximum length', () => {
Pq apagou o teste que coloca os `...`?

2023-07-05 12:05 UTC, ivanguimam requested changes

2023-07-05 12:05 UTC, ivanguimam commented on src/components/Iframe/test.tsx
> +  buildPath: jest.fn(() => 'https://app.perfarm.com/electronic_invoices'),
Como você mocou a função `buildPath` (o que faz sentido), precisamos fazer um arquivo de teste pra ela

2023-07-05 12:05 UTC, ivanguimam commented on src/components/Sidebar/test.tsx
> +test('should validate if menu options are visible', async () => {
Não entendi o que você deseja com esse teste

2023-07-05 20:43 UTC, deyvison-costa commented on src/components/Sidebar/test.tsx
> +test('should validate if menu options are visible', async () => {
Verifica se o title do menu estiver visível pelo menos uma das opções do menu também deve estar

2023-07-06 12:22 UTC, ivanguimam requested changes

2023-07-06 12:22 UTC, ivanguimam commented on src/commons/storage/accessToken/test.tsx
> +  it('Test setAccessToken and getAccessToken ', () => {
* Criar um `describe` para a função que você está testando e colocar o `it` dentro (semelhante ao comentário de baixo)
* it => should be return access token in storage
* limpar storage ao final do teste para garantir que ele não está influenciando no próximo

2023-07-06 12:22 UTC, ivanguimam commented on src/commons/storage/accessToken/test.tsx
> +  it('Test removeAccessToken function', () => {
```ts
describe('removeAccessToken', () => {
  if('should be remove access token in storage', () => {
    setAccessToken(ACCESS_TOKEN_KEY);

    const accessTokenBeforeRemove = localStorage.getItem(ACCESS_TOKEN_KEY);
    expect(accessTokenBeforeRemove).toEqual(ACCESS_TOKEN_KEY);

    removeAccessToken();

    const retrievedToken = localStorage.getItem(ACCESS_TOKEN_KEY);
    expect(retrievedToken).toBeNull();
  })
});
```

2023-07-06 12:22 UTC, ivanguimam commented on src/components/Sidebar/test.tsx
> +test('should validate if menu options are visible', async () => {
1. Melhorar a descrição do teste
2. Não precisa desse `else`, o correto é você configurar `expect.assertions` no teste
3. No caso esse não seria um teste da sidebar, seria um teste lá no `menuItems`, onde teriamos de fazer um teste para cada `show`

2023-07-06 12:22 UTC, ivanguimam commented on src/components/Sidebar/utils/buildIndividualCorporation/index.tsx
> +  url: `/seedzconnect2farmers/:${link.id}`,
* Essses `:` acho que não deveria estar na url
* Criar arquivo de teste para essa função

2023-07-06 12:22 UTC, ivanguimam commented on utils/start.ts
> +server.registerRoute(new GetMenuCorporations());
Cara, acho que essas duas rotas de menu rola colocar em uma pasta chamada `menu` e fazer semelhante ao `auth`

2023-07-06 16:47 UTC, deyvison-costa commented on src/components/Sidebar/test.tsx
> +test('should validate if menu options are visible', async () => {
Tenho dúvidas quanto ao 3º ponto ...

podemos fazer uma call em algum momento pra falar sobre ?

2023-07-07 14:38 UTC, ivanguimam requested changes

2023-07-07 14:38 UTC, ivanguimam commented on src/context/permissions/index.tsx
> +    if (token) {
Caso não tenha token, você deve setar o loding como false pq se não ele vai ficar com essa váriavel loading true pra sempre

2023-07-07 16:11 UTC, ivanguimam commented on src/context/permissions/index.tsx
> +    } else setLoading(false);
Usar chaves para manter o padrão

```ts
if (condition) {
} else {
}
```

2023-07-07 16:53 UTC, ivanguimam approved these changes

2023-07-07 16:54 UTC, merged