Feature/49922/toast configure
perfarm/frontend pull request #11
Opened 2023-07-11 19:00 UTC by deyvison-costa

# Título

### 49922 - toast configure

## Motivação

Informar possível erro ao usuário

## Solução proposta

Foi instalada a lib react-hot-toast e a partir dela foi feita uma configuração, seguindo o design system, para exibir uma mensagem de erro personalizada

## Informações adicionais

[49922 - toast configure](https://dev.azure.com/Seedz/D2F%20-%20Perfarm/_sprints/taskboard/Projeto%20Germinacao/D2F%20-%20Perfarm/Lateral%20menu?workitem=49922)

## Checklist:

- [x] Meu código segue os padrões definidos no projeto
- [x] Realizei uma autorrevisão do meu código
- [x] Adicionei testes que provam que minha correção é eficaz ou que meu recurso funciona
- [x] Testes de unidade novos e existentes passam localmente com minhas alterações
- [x] Meus componentes possuem storybook

2023-07-12 12:15 UTC, ivanguimam requested changes

2023-07-12 12:15 UTC, ivanguimam commented on src/commons/api/fetchMenuCorporations/index.tsx
> +    toast.error('Desculpe, encontramos um erro ao buscar seus itens no menu. Tente novamente mais tarde!');
Não é legal colocar toast na api, o ideal é que ela seja totalmente indepedende da aplicação, assim você pode chamar ela em momento diferentes da aplicação e decidir se quer ou não exibir uma mensagem para o usuário. O melhor é lançar o toast no componente que está usando a api. Aqui na verdade você deve fazer isso semelhante ao `src/commons/api/fetchPermissions`.

```ts
    if (e instanceof AxiosError && e.response) {
      throw new RequestError(e);
    }
    throw e;
```

2023-07-12 12:15 UTC, ivanguimam commented on src/commons/api/fetchMenuProducts/index.tsx
> +    toast.error('Desculpe, encontramos um erro ao buscar seus itens no menu. Tente novamente mais tarde!');
Não é legal colocar toast na api, o ideal é que ela seja totalmente indepedende da aplicação, assim você pode chamar ela em momento diferentes da aplicação e decidir se quer ou não exibir uma mensagem para o usuário. O melhor é lançar o toast no componente que está usando a api. Aqui na verdade você deve fazer isso semelhante ao `src/commons/api/fetchPermissions`.

```ts
    if (e instanceof AxiosError && e.response) {
      throw new RequestError(e);
    }
    throw e;
```

2023-07-12 12:15 UTC, ivanguimam commented on src/commons/api/fetchPermissions/index.ts
> +    toast.error('Desculpe, encontramos um erro ao buscar seu nível de permissão. Tente novamente mais tarde!');
Remover daqui

2023-07-12 12:15 UTC, ivanguimam commented on src/components/Sidebar/index.tsx
> +      <Toaster />
Cara, esse Toaster só é necessário ser colocado em um único arquivo, no caso o melhor seria no `src/pages/_app.tsx` pois esse é o arquivo inicial do projeto que é carregado em todas as páginas

2023-07-12 12:15 UTC, ivanguimam commented on src/components/Toaster/Icons/Close/index.tsx
> +      stroke={theme.colors.warningRedDark.toString()}
A cor tem de ser recebida via props, semelhante aos outros ícones

2023-07-12 12:15 UTC, ivanguimam commented on src/components/Toaster/test.tsx
> +test('renders Toaster component', () => {
Testar renderizar toast de erro e success

2023-07-12 12:15 UTC, ivanguimam commented on src/components/Toaster/index.tsx
> +                  <CloseButton onClick={() => onClose()}>
```ts
<CloseButton onClick={onClose}>
```

2023-07-12 12:15 UTC, ivanguimam commented on src/components/Toaster/index.tsx
> +          ariaProps: { closeIconColor: '#B63A3A', divisorColor: '#DB4646' },
Pegar todas essas cores no tema

2023-07-12 12:15 UTC, ivanguimam commented on src/components/Toaster/types.ts
> +export interface ToastOptions {
Cara, acho que não precisamos disso, pq você ta falando que esse componente recebe como props um `ToastOptions` se ele nem é utilizado no componente?

2023-07-12 12:33 UTC, deyvison-costa commented on src/components/Toaster/types.ts
> +export interface ToastOptions {
Precisei desse tipo porque o conteúdo de airProps "{ closeIconColor: '#B63A3A', divisorColor: '#DB4646' } " não existe nativamente na lib...
aí acaba dando erro se não incluir essas duas opções no type

2023-07-12 12:37 UTC, deyvison-costa commented on src/components/Toaster/test.tsx
> +test('renders Toaster component', () => {
teremos toast de success ?

2023-07-12 17:53 UTC, ivanguimam requested changes

2023-07-12 17:53 UTC, ivanguimam commented on src/components/Toaster/types.ts
> +  toastOptions?: ToastOptions;
Não é necessário pois o componente não recebe um options como props

2023-07-14 11:59 UTC, ivanguimam requested changes

2023-07-14 11:59 UTC, ivanguimam commented on src/components/Toaster/optionsColor/index.ts
> +
Por que desta linha em branco?

2023-07-14 11:59 UTC, ivanguimam commented on src/components/Toaster/index.tsx
> +const { warningRedAlert, warningRedDark, warningRedHover, white } = optionColors;
Por que você salvou as cores do tema em um outro arquivo ao invés de utilizar direto nesse?

2023-07-16 03:18 UTC, deyvison-costa commented on src/components/Toaster/optionsColor/index.ts
> +
optionColor foi removido.

2023-07-16 03:23 UTC, deyvison-costa commented on src/components/Toaster/index.tsx
> +const { warningRedAlert, warningRedDark, warningRedHover, white } = optionColors;
Adicionei esse arquivo para tentar melhorar a estética o código, mas já foi removido.

2023-07-17 14:51 UTC, ivanguimam requested changes

2023-07-17 14:51 UTC, ivanguimam commented on src/components/Sidebar/index.tsx
> +    <Fragment>
Esse `Fragment` é desnecessário

2023-07-17 14:51 UTC, ivanguimam commented on src/components/Toaster/index.tsx
> +          background: '#363636',
Esse cara não tem no nosso desgin pattern?

2023-07-17 14:51 UTC, ivanguimam commented on src/components/Toaster/index.tsx
> +    toastOptions={
Podemos colocar essas configurações do `toastOptions` fora do componente já que elas não dependem de nenhuma props

```tsx
const toastOptions: ToastOptions = {...}

export const Toaster: FC<Props> = ({ gutter = 3, position = 'top-right' }) => (
  <ReactHotToast
    gutter={gutter}
    position={position}
    toastOptions={toastOptions}
```

2023-07-17 14:51 UTC, ivanguimam commented on src/components/Toaster/test.tsx
> +test('renders Toaster component', () => {
Por enquanto não, somente de erro, então fazer um teste para mostrar a exibição do de erro

2023-07-17 14:56 UTC, deyvison-costa commented on src/components/Toaster/index.tsx
> +          background: '#363636',
Não.
No nosso them enão tem essa cor.
Devo incluir ?

2023-07-17 14:56 UTC, deyvison-costa commented on src/components/Sidebar/index.tsx
> +    <Fragment>
Removido.

2023-07-18 17:20 UTC, ivanguimam commented on src/components/Toaster/index.tsx
> +          const onClose = (e: React.MouseEvent<HTMLButtonElement>) => {
Cara, não precisa dessa complicação toda para remover o toast, na variável `toast` da linha 35 já tem o id dele

```ts
const onClose = useCallback(() => {
  reactHotToast.remove(toast.id);
}, []);
```

2023-07-18 17:51 UTC, merged

2023-07-19 01:51 UTC, deyvison-costa commented on src/components/Toaster/index.tsx
> +          const onClose = (e: React.MouseEvent<HTMLButtonElement>) => {
Então, como eu disse em outro momento "só removi a function do jeito que você pôs acima porque o lint reclama que tem um useCallback dentro de outro callback que no caso é a function anonima da linha 42 em diante."

inclusive estava exatamente da forma que você sugeriu acima.

devo desabilitar essa regra lá no arquivo de lint ?

![image](https://github.com/perfarm/frontend/assets/127112215/48b20590-622c-4248-9c53-3ba1dcd6d191)