Feature/60167/recursive sidebar
perfarm/frontend pull request #25
Opened 2023-10-09 19:00 UTC by deyvison-costa

# Título

### 60167 - Tornar recursivo o menu lateral

## Motivação

Melhorar a performance do menu lateral

## Solução proposta

Foi feita uma refatoração do antigo menu para que o mesmo se tornasse mais eficiente.

## Informações adicionais

 [60167 - Tornar recursivo o menu lateral](https://dev.azure.com/Seedz/D2F%20-%20DirectToFarmer/_sprints/taskboard/Perfarm/D2F%20-%20DirectToFarmer/Sprint%2004?System.AssignedTo=deyvison.costa%40seedz.ag&workitem=60167)

## Checklist:

- [x] Meu código segue os padrões definidos no projeto
- [x] Realizei uma autorrevisão do meu código
- [x] Adicionei testes que provam que minha correção é eficaz ou que meu recurso funciona
- [x] Testes de unidade novos e existentes passam localmente com minhas alterações
- [x] Meus componentes possuem storybook

2023-10-11 11:51 UTC, ivanguimam requested changes

2023-10-11 11:51 UTC, ivanguimam commented on src/components/Sidebar/SidebarItems/index.tsx
Colocar o nome do componente no singular

2023-10-11 11:51 UTC, ivanguimam commented on src/components/Sidebar/SidebarItems/index.tsx
> +import { linkStyle, LinkText } from '../style';
Arrumar importação

2023-10-11 11:51 UTC, ivanguimam commented on src/components/Sidebar/SidebarItems/index.tsx
> +import { truncateLabel } from '../utils/truncateLabel';
Arrumar importação

2023-10-11 11:51 UTC, ivanguimam commented on src/components/Sidebar/SidebarItems/index.tsx
> +        const DynamicComponent = subLinks?.length ? SubMenu : MenuItem;
Cara, o ideal é que o nome de seus components/variáveis tenham um nome que explique o que ele signifique, nesse caso `DynamicComponent` não deixa claro o que ele é, o ideal aqui seria ser `MenuItem`, `Item` algo do tipo

2023-10-11 11:51 UTC, ivanguimam commented on src/components/Sidebar/SidebarItems/index.tsx
> +          <RootLink
Esse `RootLink` eu fiz ele na correria então não me preocupei muito com o nome dele, mas um nome melhor seria `CollapseLInk` ou algo próximo a isso

2023-10-11 11:51 UTC, ivanguimam commented on src/components/Sidebar/SidebarItems/index.tsx
> +                {truncateLabel(label)}
Esse truncate a gente pode fazer no pré-processamento (buildMenu) do menu, colocar uma outra propriedade chamada `summarizedLabel` assim a gente não precisa executar esse `truncateLabel` a cada rerender do componente

2023-10-11 11:51 UTC, ivanguimam commented on src/components/Sidebar/SidebarItems/types.ts
> +  iframeURLPath?: any;
Isso é uma string e é obrigatório

2023-10-11 11:51 UTC, ivanguimam commented on src/components/Sidebar/SidebarItems/types.ts
> +  currentPath?: string;
Isso é obrigatório

2023-10-11 11:51 UTC, ivanguimam commented on src/components/Sidebar/linkItems/index.tsx
Acho que podemos chama isso de menuItems mesmo, em todo lugar ta sendo chamado assim, até o componente `SidebarItem`

2023-10-11 11:51 UTC, ivanguimam commented on src/components/Sidebar/stories.tsx
> +} as Meta;
Pq retirou o props daqui?

2023-10-11 11:51 UTC, ivanguimam commented on src/components/Sidebar/stories.tsx
> -const Template: StoryFn<Props> = (args) => <Sidebar {...args} />;
Pq retirou o props daqui?

2023-10-11 11:51 UTC, ivanguimam commented on src/components/Sidebar/style.ts
> +  '.css-hzmj03::-webkit-scrollbar': {
Cara essas classes geradas pelo stitches são dinâmicas, caso você altere qualquer propriedade do componente elas são geradas novamente com outro nome e ai isso pararia de funcionar, então não é recomendado fazer estilização assim. Pq você fez isso? Seu objetivo é esconder o scroll?

2023-10-11 11:56 UTC, deyvison-costa commented on src/components/Sidebar/style.ts
> +  '.css-hzmj03::-webkit-scrollbar': {
Sim meu objetivo é esconder o scroll.
mas vou pensar numa forma melhor para fazer isso.

2023-10-11 11:58 UTC, deyvison-costa commented on src/components/Sidebar/stories.tsx
> -const Template: StoryFn<Props> = (args) => <Sidebar {...args} />;
porque o componente Sidebar não recebe props

2023-10-11 11:58 UTC, deyvison-costa commented on src/components/Sidebar/stories.tsx
> +} as Meta;
porque o componente Sidebar não recebe props

2023-10-16 17:46 UTC, ivanguimam commented on src/components/Sidebar/SidebarItem/components/CollapseLInk/index.tsx
> +  const truncatedLabel = useMemo(() => summarizedLabel || truncateLabel(label), [label, summarizedLabel]);
Acho que isso não é mais necessário já que resolvemos isso no pré-compilamento do menu, basta exibir o `summarizedLabel`

2023-10-16 17:47 UTC, ivanguimam commented on src/components/Sidebar/SidebarItem/index.tsx
> +        console.log('AQUI => ', summarizedLabel);
??

2023-10-16 17:49 UTC, ivanguimam commented on src/components/Sidebar/SidebarItem/index.tsx
> +                {summarizedLabel || truncateLabel(label)}
Aqui seria exibir somente o `summarizedLabel`. já que estamos fazendo esse `truncateLabel` no pré-processamento do menu em todo mundo

2023-10-16 17:50 UTC, ivanguimam commented on src/components/Sidebar/utils.ts
> +    if (!link.isExternalUrl) {
Cara, podemos aplica essa regra `link.summarizedLabel = truncateLabel(link.label);` em todo mundo, até mesmo em quem é link externo para evitar que quebre o menu

2023-10-16 17:52 UTC, ivanguimam commented on src/components/Sidebar/utils.ts
> +    if (link.links) {
`if (link.links.length) {`

2023-10-17 11:43 UTC, ivanguimam requested changes

2023-10-17 11:43 UTC, ivanguimam commented on src/components/Sidebar/SidebarItem/components/CollapseLInk/index.tsx
> +  const truncatedLabel = useMemo(() => summarizedLabel, [summarizedLabel]);
Isso aqui não é necessário, você pode passar o `summarizedLabel` direto na linha 49

2023-10-17 11:43 UTC, ivanguimam commented on src/components/Sidebar/SidebarItem/index.tsx
> +        const Item = subLinks?.length ? SubMenu : MenuItem;
Você pode declarar um default value para `subLinks`, assim não precisa do operador `?.`.
```
{links.map(({ icon: Icon, isExternalUrl, label, links: subLinks = [], query = {}, summarizedLabel, url }) => {

const Item = subLinks.length ? SubMenu : MenuItem;
```

2023-10-17 11:43 UTC, ivanguimam commented on src/components/Sidebar/SidebarItem/index.tsx
> +            {subLinks?.length ? (
Você pode declarar um default value para `subLinks`, assim não precisa do operador `?.`.
```
{links.map(({ icon: Icon, isExternalUrl, label, links: subLinks = [], query = {}, summarizedLabel, url }) => {

{subLinks?.length ? (
```

2023-10-17 11:43 UTC, ivanguimam commented on src/components/Sidebar/SidebarItem/index.tsx
> +        const linkComponent = subLinks?.length ? (
Você pode declarar um default value para `subLinks`, assim não precisa do operador `?.`.
```
{links.map(({ icon: Icon, isExternalUrl, label, links: subLinks = [], query = {}, summarizedLabel, url }) => {

const linkComponent = subLinks?.length ? (
```

2023-10-17 19:18 UTC, merged