feat: create iframe component
perfarm/frontend pull request #7
Opened 2023-06-26 12:24 UTC by deyvison-costa

# Título

### 49179 - Exibir em tela os componentes sidebar e iframe 

## Motivação

Melhorar a experiência do usuário através de uma navegação mais fácil.

## Solução proposta

Foi feita uma interação entre Sidebar e Iframe para facilitar a navegação do usuário.

## Informações adicionais

 
 Card no Azure
- [49179 - Exibir em tela os componentes sidebar e iframe](https://dev.azure.com/Seedz/D2F%20-%20Perfarm/_sprints/taskboard/Projeto%20Germinacao/D2F%20-%20Perfarm/Lateral%20menu?workitem=49179)

## Checklist:

- [x] Meu código segue os padrões definidos no projeto
- [x] Realizei uma autorrevisão do meu código
- [x] Adicionei testes que provam que minha correção é eficaz ou que meu recurso funciona
- [x] Testes de unidade novos e existentes passam localmente com minhas alterações
- [x] Meus componentes possuem storybook

2023-06-26 12:37 UTC, ivanguimam requested changes

2023-06-26 12:37 UTC, ivanguimam commented on src/components/Iframe/index.tsx
> +  const handlePath = (path: string) => {
Cara, já podemos colocar o `PERFARM_URL` aqui mesmo pra não ficar concatenando ele no iframe

```ts
const handlePath = (path: string) => {
  const url = path.replace('/app/', '');
  return `${PERFARM_URL}/${url}`;
};
```

2023-06-26 12:37 UTC, ivanguimam commented on src/components/Iframe/index.tsx
> +    <React.Fragment>
Pra que desse Fragment?

2023-06-26 12:37 UTC, ivanguimam commented on src/components/Sidebar/index.tsx
> +      collapsedWidth={'85px'}
collapsedWidth="85px"

2023-06-28 11:58 UTC, ivanguimam requested changes

2023-06-28 11:58 UTC, ivanguimam commented on src/components/Iframe/index.tsx
> +  const handlePath = (path: string) => {
* Podemos colocar essa função fora do componente, já que ela não depende de nada que tem dentro dele
* Acho que um nome melhor para ela ficaria `buildPath` ou `buildUrl`
* E faltou um ponto que eu esquecide de mencionar, a gente precisa add o query params `navbar-version=V2` na url, pra gente poder mostrar a nova navbar no sistema atual

```ts
const url = new URL(path.replace('/app/', ''), PERFARM_URL);

if (!url.has('navbar-version') {
  url.append('navbar-version', 'V2');
}

return url.toString();
```

2023-06-28 15:45 UTC, deyvison-costa commented on src/components/Iframe/index.tsx
> +  const handlePath = (path: string) => {
Acredito que o objetivo do if é verificar a existência do parâmetro 'navbar-version'. Se sim, isso só será possível se usarmos o searchParams, como demonstrado abaixo. Não dá pra usar o .has na variável url (_!url.has_)

```typescript
 const url = new URL(path.replace('/app/', ''), PERFARM_URL);

  if (!url.searchParams.has('navbar-version')) {
    url.searchParams.append('navbar-version', 'V2');
  }

  return url.toString();
```

2023-06-28 16:45 UTC, ivanguimam approved these changes

2023-06-28 16:45 UTC, merged